name: Java CI with Maven

# This workflow runs on any push to the 'main' branch or any pull request
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up the correct JDK version (24 in our case)
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      # Step 3: Build the project with Maven. This will also compile, test, and generate docs.
      - name: Build with Maven
        run: mvn -B package --file pom.xml